import type { Metadata } from "next";
import { Geist, Geist_Mono, Exo_2, Kanit, Open_Sans } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const exo2 = Exo_2({
  variable: '--font-exo-2',
  subsets: ['latin'],
})

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
})

const kanit = Kanit({ variable: "--font-kanit", weight: "800" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${openSans.variable} ${exo2.variable}  ${kanit.variable} flex flex-col h-screen antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
